#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt


def fopen_read(files):
    """read from file"""
    with open(files, "r", encoding="utf-8") as file:
        lines = file.readlines()
    factor_number = []
    for line in lines:
        factor_number.append(int(line))
    return factor_number


def search_and_count(n):
    """factor each given n"""
    for i in range(1, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break


def factor_list(ls):
    """factor each num"""
    for i in ls:
        search_and_count(i)


if len(argv) == 2:
    factor_list(fopen_read(argv[1]))
