#!/usr/bin/env python3

from sys import argv
from math import sqrt
"""Facorization numbers"""
"""Read file"""
def fopen_read(file):
    with open(file, "r", encoding="utf-8") as file:
        """Add to array"""
        lines = file.readlines()
    factor_number = []
    for line in lines:
        factor_number.append(int(line))
    return factor_number


def search_and_count(n):
    """Factor every n given"""
    for j in range(1, n):
        if n == ((n // j) * j):
            print("{}={}*{}".format(n, (n // j), j))
            break


def factor_list(ls):

    for j in ls:
        search_and_count(j)


if len(argv) == 2:
    factor_list(fopen_read(argv[1]))
